apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: <your-nexus-url>/my-app:latest  # Replace with your Nexus URL
          ports:
            - containerPort: 8080  # Change if your app runs on a different port

